"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const STORAGE_KEY = "appLanguage";

const translations: Record<Language, Record<string, string>> = {
  fr: {
    "common.french": "FR",
    "common.english": "EN",
    "common.loading": "Chargement...",

    "auth.login.title": "Connexion",
    "auth.login.email": "Adresse e-mail",
    "auth.login.password": "Mot de passe",
    "auth.login.forgot": "Mot de passe oublié ?",
    "auth.login.remember": "Rester connecté",
    "auth.login.submit": "Se connecter",
    "auth.login.loading": "Connexion en cours...",
    "auth.login.fillAll": "Veuillez remplir tous les champs",
    "auth.login.network": "Erreur réseau. Vérifiez votre connexion.",
    "auth.login.invalidResponse": "Le point de connexion a renvoyé une réponse non JSON. Vérifiez NEXT_PUBLIC_API_URL (actuel : {baseUrl}).",

    "auth.forgot.title": "Mot de passe oublié ?",
    "auth.forgot.subtitle": "Pas de souci, nous allons vous envoyer des instructions de réinitialisation.",
    "auth.forgot.email": "Adresse e-mail",
    "auth.forgot.submit": "Envoyer le lien",
    "auth.forgot.sending": "Envoi en cours...",
    "auth.forgot.back": "← Retour à la connexion",
    "auth.forgot.checkEmail": "Vérifiez votre e-mail",
    "auth.forgot.checkEmailBody": "Nous avons envoyé un lien de réinitialisation à votre adresse e-mail.",
    "auth.forgot.tip": "Astuce : le lien expire dans 24 heures. Vérifiez aussi vos spams.",
    "auth.forgot.remember": "Vous vous souvenez de votre mot de passe ?",
    "auth.forgot.backToLogin": "Retour à la connexion",

    "auth.reset.title": "Définir un nouveau mot de passe",
    "auth.reset.subtitle": "Saisissez votre nouveau mot de passe ci-dessous.",
    "auth.reset.newPassword": "Nouveau mot de passe",
    "auth.reset.confirmPassword": "Confirmer le mot de passe",
    "auth.reset.submit": "Réinitialiser le mot de passe",
    "auth.reset.loading": "Réinitialisation...",
    "auth.reset.back": "← Retour à la connexion",
    "auth.reset.invalidTitle": "Lien invalide",
    "auth.reset.invalidBody": "Le lien est invalide ou expiré. Veuillez en demander un nouveau.",
    "auth.reset.requestNew": "Demander un nouveau lien",
    "auth.reset.successTitle": "Mot de passe réinitialisé",
    "auth.reset.successBody": "Votre mot de passe a été réinitialisé avec succès.",
    "auth.reset.goLogin": "Aller à la connexion",
    "auth.reset.passwordHint": "Au moins 8 caractères",

    "dashboard.title": "Vue d'ensemble",
    "dashboard.subtitle": "RHpro",
    "dashboard.role": "Rôle",
    "dashboard.notifications": "Notifications",
    "dashboard.markAllRead": "Tout marquer comme lu",
    "dashboard.new": "Nouveau",
    "dashboard.noNotifications": "Aucune notification",
    "dashboard.allCaughtUp": "Vous êtes à jour !",
    "dashboard.viewAllNotifications": "Voir toutes les notifications",
    "dashboard.logout": "Déconnexion",
    "dashboard.user": "Utilisateur",
    "dashboard.teamMember": "Membre de l'équipe",
    "dashboard.welcomeBack": "Bon retour",
    "dashboard.todayOverview": "Voici un aperçu de votre activité aujourd'hui.",
    "dashboard.role.admin": "Vue administrateur",
    "dashboard.role.manager": "Vue manager",
    "dashboard.role.collaborator": "Vue collaborateur",
    "dashboard.stat.totalEmployees": "Employés total",
    "dashboard.stat.teamMembers": "Membres d'équipe",
    "dashboard.stat.activeProjects": "Projets actifs",
    "dashboard.stat.pendingRequests": "Demandes en attente",
    "dashboard.stat.timesheetsSubmitted": "Feuilles soumises",
    "dashboard.stat.toApprove": "À approuver",
    "dashboard.stat.teamHoursWeek": "Heures équipe/semaine",
    "dashboard.stat.weeklyHours": "Heures hebdomadaires",
    "dashboard.stat.timesheetStatus": "Statut timesheet",
    "dashboard.recentActivity": "Activité récente",
    "dashboard.viewAll": "Voir tout",
    "dashboard.focusTitle": "Éléments clés",
    "dashboard.activity.admin.title1": "Nouvel employé créé",
    "dashboard.activity.admin.description1": "Un nouveau collaborateur a été ajouté avec succès.",
    "dashboard.activity.admin.title2": "Rôle mis à jour",
    "dashboard.activity.admin.description2": "Des permissions ont été ajustées sur un rôle.",
    "dashboard.activity.manager.title1": "Timesheet à valider",
    "dashboard.activity.manager.description1": "Une feuille de temps de l'équipe attend votre validation.",
    "dashboard.activity.manager.title2": "Demande de congé reçue",
    "dashboard.activity.manager.description2": "Une nouvelle demande de congé nécessite votre décision.",
    "dashboard.activity.collaborator.title1": "Demande de congé approuvée",
    "dashboard.activity.collaborator.description1": "Votre demande de congé a été validée.",
    "dashboard.activity.collaborator.title2": "Nouveau projet assigné",
    "dashboard.activity.collaborator.description2": "Vous avez été affecté à un nouveau projet.",
    "dashboard.activity.time1h": "il y a 1h",
    "dashboard.activity.time2h": "il y a 2h",
    "dashboard.activity.time4h": "il y a 4h",
    "dashboard.activity.time5h": "il y a 5h",
    "dashboard.focus.admin.item1": "Conformité des documents",
    "dashboard.focus.admin.item2": "Suivi des validations",
    "dashboard.focus.admin.item3": "Onboarding collaborateurs",
    "dashboard.focus.manager.item1": "Validation des timesheets",
    "dashboard.focus.manager.item2": "Planification des congés",
    "dashboard.focus.manager.item3": "Suivi charge d'équipe",
    "dashboard.focus.collaborator.item1": "Avancement des tâches",
    "dashboard.focus.collaborator.item2": "Demandes personnelles",
    "dashboard.focus.collaborator.item3": "Temps projet saisi",

    "sidebar.appSubtitle": "RHpro",
    "sidebar.dashboard": "Tableau de bord",
    "sidebar.employees": "Employés",
    "sidebar.projects": "Projets",
    "sidebar.rolesDepots": "Rôles & Dépôts",
    "sidebar.requests": "Demandes",
    "sidebar.settings": "Paramètres",
    "sidebar.timesheets": "Feuilles de temps",
    "sidebar.approvals": "Approbations",
    "sidebar.myDossier": "Mon dossier",
    "sidebar.evaluations": "Évaluations",
    "sidebar.administrator": "Administrateur",
    "sidebar.manager": "Manager",
    "sidebar.collaborator": "Collaborateur",
    "sidebar.user": "Utilisateur",

    "timesheets.title": "Feuilles de temps",
    "timesheets.subtitle": "Suivi hebdomadaire des heures, soumission et validation.",
    "timesheets.quickActions": "Actions rapides",
    "timesheets.collaboratorHint": "Saisissez vos heures par projet, sauvegardez en brouillon puis soumettez à votre manager.",
    "timesheets.managerHint": "Consultez les feuilles soumises, puis approuvez ou rejetez avec commentaire.",
    "timesheets.adminHint": "Vue consolidée des feuilles de temps, heures projet et heures supplémentaires.",
    "timesheets.pendingTitle": "Feuilles en attente de validation",
    "timesheets.reportingTitle": "Vue globale et reporting",
    "timesheets.openApprovals": "Ouvrir la file des validations",
    "timesheets.action.saveDraft": "Sauvegarder brouillon",
    "timesheets.action.submit": "Soumettre",
    "timesheets.card.weekHours": "Heures semaine",
    "timesheets.card.overtime": "Heures supplémentaires",
    "timesheets.card.status": "Statut",
    "timesheets.card.pendingApprovals": "À approuver",
    "timesheets.card.teamHours": "Heures équipe",
    "timesheets.card.teamOvertime": "HS équipe",
    "timesheets.card.submittedThisWeek": "Soumises cette semaine",
    "timesheets.card.approvedThisWeek": "Approuvées cette semaine",
    "timesheets.card.globalHours": "Heures globales",
    "timesheets.card.globalOvertime": "HS globales",
    "timesheets.field.weekStart": "Début de semaine",
    "timesheets.field.entryMode": "Mode de saisie",
    "timesheets.field.project": "Sélectionner un projet",
    "timesheets.field.projectId": "ID Projet",
    "timesheets.field.task": "Tâche",
    "timesheets.field.hours": "Heures",
    "timesheets.field.description": "Description d'activité",
    "timesheets.field.comments": "Commentaires",
    "timesheets.field.managerComment": "Commentaire manager (obligatoire pour rejet)",
    "timesheets.mode.simple": "Saisie simple",
    "timesheets.mode.detailed": "Saisie détaillée",
    "timesheets.action.addLine": "Ajouter ligne",
    "timesheets.action.removeLine": "Supprimer ligne",
    "timesheets.action.loadQueue": "Charger file manager",
    "timesheets.action.approve": "Approuver",
    "timesheets.action.reject": "Rejeter",
    "timesheets.action.loadReport": "Charger rapport",
    "timesheets.action.exportExcel": "Exporter Excel",
    "timesheets.action.exportPdf": "Exporter PDF",
    "timesheets.monthlyReport": "Rapport mensuel",
    "timesheets.report.totalTimesheets": "Feuilles totales",
    "timesheets.report.totalHours": "Heures totales",
    "timesheets.report.overtime": "Heures supplémentaires",
    "timesheets.report.empty": "Aucun rapport chargé.",
    "timesheets.success.saved": "Brouillon sauvegardé.",
    "timesheets.success.submitted": "Timesheet soumise pour validation.",
    "timesheets.success.approved": "Timesheet approuvée.",
    "timesheets.success.rejected": "Timesheet rejetée.",
    "timesheets.success.exported": "Export généré.",
    "timesheets.error.noUser": "Utilisateur introuvable.",
    "timesheets.error.emptyEntries": "Ajoutez au moins une ligne valide.",
    "timesheets.error.saveFailed": "Échec de sauvegarde du brouillon.",
    "timesheets.error.saveBeforeSubmit": "Sauvegardez le brouillon avant soumission.",
    "timesheets.error.submitFailed": "Échec de soumission.",
    "timesheets.error.loadQueueFailed": "Échec du chargement des validations.",
    "timesheets.error.approveFailed": "Échec de l'approbation.",
    "timesheets.error.rejectNeedsComment": "Le commentaire est requis pour rejeter.",
    "timesheets.error.rejectFailed": "Échec du rejet.",
    "timesheets.error.reportFailed": "Échec du chargement du rapport.",
    "timesheets.error.noSession": "Session expirée. Reconnectez-vous.",
    "timesheets.error.exportFailed": "Échec de l'export.",
    "timesheets.error.noProjects": "Aucun projet disponible dans la base.",

    "landing.features": "Fonctionnalités",
    "landing.workflow": "Workflow",
    "landing.security": "Sécurité",
    "landing.aiRoadmap": "Feuille de route IA",
    "landing.contact": "Contact",
    "landing.login": "Connexion",
    "landing.getStarted": "Commencer",
    "landing.brand": "RHpro",
  },
  en: {
    "common.french": "FR",
    "common.english": "EN",
    "common.loading": "Loading...",

    "auth.login.title": "Sign In",
    "auth.login.email": "Email Address",
    "auth.login.password": "Password",
    "auth.login.forgot": "Forgot password?",
    "auth.login.remember": "Keep me logged in",
    "auth.login.submit": "Sign In",
    "auth.login.loading": "Logging in...",
    "auth.login.fillAll": "Please fill in all fields",
    "auth.login.network": "Network error. Please check your connection.",
    "auth.login.invalidResponse": "Login endpoint returned non-JSON response. Check NEXT_PUBLIC_API_URL (current: {baseUrl}).",

    "auth.forgot.title": "Forgot password?",
    "auth.forgot.subtitle": "No worries, we’ll send you reset instructions.",
    "auth.forgot.email": "Email Address",
    "auth.forgot.submit": "Send Reset Link",
    "auth.forgot.sending": "Sending...",
    "auth.forgot.back": "← Back to login",
    "auth.forgot.checkEmail": "Check your email",
    "auth.forgot.checkEmailBody": "We have sent a password reset link to your email address.",
    "auth.forgot.tip": "Tip: The reset link will expire in 24 hours. Check your spam folder too.",
    "auth.forgot.remember": "Remember your password?",
    "auth.forgot.backToLogin": "Back to login",

    "auth.reset.title": "Set New Password",
    "auth.reset.subtitle": "Enter your new password below.",
    "auth.reset.newPassword": "New Password",
    "auth.reset.confirmPassword": "Confirm Password",
    "auth.reset.submit": "Reset Password",
    "auth.reset.loading": "Resetting...",
    "auth.reset.back": "← Back to login",
    "auth.reset.invalidTitle": "Invalid Reset Link",
    "auth.reset.invalidBody": "The password reset link is invalid or has expired. Please request a new one.",
    "auth.reset.requestNew": "Request New Reset Link",
    "auth.reset.successTitle": "Password Reset Successful",
    "auth.reset.successBody": "Your password has been successfully reset.",
    "auth.reset.goLogin": "Go to Login",
    "auth.reset.passwordHint": "At least 8 characters",

    "dashboard.title": "Dashboard Overview",
    "dashboard.subtitle": "RHpro",
    "dashboard.role": "Role",
    "dashboard.notifications": "Notifications",
    "dashboard.markAllRead": "Mark all as read",
    "dashboard.new": "New",
    "dashboard.noNotifications": "No notifications",
    "dashboard.allCaughtUp": "You're all caught up!",
    "dashboard.viewAllNotifications": "View all notifications",
    "dashboard.logout": "Logout",
    "dashboard.user": "User",
    "dashboard.teamMember": "Team Member",
    "dashboard.welcomeBack": "Welcome back",
    "dashboard.todayOverview": "Here is an overview of your activity today.",
    "dashboard.role.admin": "Administrator view",
    "dashboard.role.manager": "Manager view",
    "dashboard.role.collaborator": "Collaborator view",
    "dashboard.stat.totalEmployees": "Total employees",
    "dashboard.stat.teamMembers": "Team members",
    "dashboard.stat.activeProjects": "Active projects",
    "dashboard.stat.pendingRequests": "Pending requests",
    "dashboard.stat.timesheetsSubmitted": "Timesheets submitted",
    "dashboard.stat.toApprove": "To approve",
    "dashboard.stat.teamHoursWeek": "Team hours/week",
    "dashboard.stat.weeklyHours": "Weekly hours",
    "dashboard.stat.timesheetStatus": "Timesheet status",
    "dashboard.recentActivity": "Recent activity",
    "dashboard.viewAll": "View all",
    "dashboard.focusTitle": "Focus items",
    "dashboard.activity.admin.title1": "New employee created",
    "dashboard.activity.admin.description1": "A new collaborator has been added successfully.",
    "dashboard.activity.admin.title2": "Role updated",
    "dashboard.activity.admin.description2": "Permissions were adjusted on a role.",
    "dashboard.activity.manager.title1": "Timesheet waiting approval",
    "dashboard.activity.manager.description1": "A team timesheet is waiting for your validation.",
    "dashboard.activity.manager.title2": "Leave request received",
    "dashboard.activity.manager.description2": "A new leave request needs your decision.",
    "dashboard.activity.collaborator.title1": "Leave request approved",
    "dashboard.activity.collaborator.description1": "Your leave request has been approved.",
    "dashboard.activity.collaborator.title2": "New project assigned",
    "dashboard.activity.collaborator.description2": "You have been assigned to a new project.",
    "dashboard.activity.time1h": "1h ago",
    "dashboard.activity.time2h": "2h ago",
    "dashboard.activity.time4h": "4h ago",
    "dashboard.activity.time5h": "5h ago",
    "dashboard.focus.admin.item1": "Document compliance",
    "dashboard.focus.admin.item2": "Approval tracking",
    "dashboard.focus.admin.item3": "Employee onboarding",
    "dashboard.focus.manager.item1": "Timesheet approvals",
    "dashboard.focus.manager.item2": "Leave planning",
    "dashboard.focus.manager.item3": "Team workload tracking",
    "dashboard.focus.collaborator.item1": "Task progress",
    "dashboard.focus.collaborator.item2": "Personal requests",
    "dashboard.focus.collaborator.item3": "Logged project time",

    "sidebar.appSubtitle": "RHpro",
    "sidebar.dashboard": "Dashboard",
    "sidebar.employees": "Employees",
    "sidebar.projects": "Projects",
    "sidebar.rolesDepots": "Roles & Depots",
    "sidebar.requests": "Requests",
    "sidebar.settings": "Settings",
    "sidebar.timesheets": "Timesheets",
    "sidebar.approvals": "Approvals",
    "sidebar.myDossier": "My Dossier",
    "sidebar.evaluations": "Evaluations",
    "sidebar.administrator": "Administrator",
    "sidebar.manager": "Manager",
    "sidebar.collaborator": "Collaborator",
    "sidebar.user": "User",

    "timesheets.title": "Timesheets",
    "timesheets.subtitle": "Weekly time tracking, submission, and approval workflow.",
    "timesheets.quickActions": "Quick actions",
    "timesheets.collaboratorHint": "Log your hours by project, save as draft, then submit to your manager.",
    "timesheets.managerHint": "Review submitted timesheets and approve or reject with comments.",
    "timesheets.adminHint": "Consolidated view of timesheets, project hours, and overtime.",
    "timesheets.pendingTitle": "Timesheets pending approval",
    "timesheets.reportingTitle": "Global view and reporting",
    "timesheets.openApprovals": "Open approval queue",
    "timesheets.action.saveDraft": "Save draft",
    "timesheets.action.submit": "Submit",
    "timesheets.card.weekHours": "Weekly hours",
    "timesheets.card.overtime": "Overtime hours",
    "timesheets.card.status": "Status",
    "timesheets.card.pendingApprovals": "Pending approvals",
    "timesheets.card.teamHours": "Team hours",
    "timesheets.card.teamOvertime": "Team overtime",
    "timesheets.card.submittedThisWeek": "Submitted this week",
    "timesheets.card.approvedThisWeek": "Approved this week",
    "timesheets.card.globalHours": "Global hours",
    "timesheets.card.globalOvertime": "Global overtime",
    "timesheets.field.weekStart": "Week start",
    "timesheets.field.entryMode": "Entry mode",
    "timesheets.field.project": "Select project",
    "timesheets.field.projectId": "Project ID",
    "timesheets.field.task": "Task",
    "timesheets.field.hours": "Hours",
    "timesheets.field.description": "Activity description",
    "timesheets.field.comments": "Comments",
    "timesheets.field.managerComment": "Manager comment (required for rejection)",
    "timesheets.mode.simple": "Simple entry",
    "timesheets.mode.detailed": "Detailed entry",
    "timesheets.action.addLine": "Add line",
    "timesheets.action.removeLine": "Remove line",
    "timesheets.action.loadQueue": "Load manager queue",
    "timesheets.action.approve": "Approve",
    "timesheets.action.reject": "Reject",
    "timesheets.action.loadReport": "Load report",
    "timesheets.action.exportExcel": "Export Excel",
    "timesheets.action.exportPdf": "Export PDF",
    "timesheets.monthlyReport": "Monthly report",
    "timesheets.report.totalTimesheets": "Total timesheets",
    "timesheets.report.totalHours": "Total hours",
    "timesheets.report.overtime": "Overtime hours",
    "timesheets.report.empty": "No report loaded yet.",
    "timesheets.success.saved": "Draft saved.",
    "timesheets.success.submitted": "Timesheet submitted for approval.",
    "timesheets.success.approved": "Timesheet approved.",
    "timesheets.success.rejected": "Timesheet rejected.",
    "timesheets.success.exported": "Export generated.",
    "timesheets.error.noUser": "User not found.",
    "timesheets.error.emptyEntries": "Add at least one valid line.",
    "timesheets.error.saveFailed": "Failed to save draft.",
    "timesheets.error.saveBeforeSubmit": "Save draft before submitting.",
    "timesheets.error.submitFailed": "Failed to submit timesheet.",
    "timesheets.error.loadQueueFailed": "Failed to load manager queue.",
    "timesheets.error.approveFailed": "Failed to approve timesheet.",
    "timesheets.error.rejectNeedsComment": "Comment is required to reject.",
    "timesheets.error.rejectFailed": "Failed to reject timesheet.",
    "timesheets.error.reportFailed": "Failed to load report.",
    "timesheets.error.noSession": "Session expired. Please log in again.",
    "timesheets.error.exportFailed": "Failed to export file.",
    "timesheets.error.noProjects": "No projects available in the database.",

    "landing.features": "Features",
    "landing.workflow": "Workflow",
    "landing.security": "Security",
    "landing.aiRoadmap": "AI Roadmap",
    "landing.contact": "Contact",
    "landing.login": "Login",
    "landing.getStarted": "Get Started",
    "landing.brand": "RHpro",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") {
      return "fr";
    }

    const saved = window.localStorage.getItem(STORAGE_KEY) as Language | null;
    return saved === "fr" || saved === "en" ? saved : "fr";
  });

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] ?? key,
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

